### PR TITLE
Mexican Spanish translation

### PR DESCRIPTION
**Pull request by TheLegendofSaram**

### CODE REVIEW

**Comment by opekope2** [comment]
I'll give a shoutout in the readme, Modrinth, and CurseForge page. Is the GitHub profile link OK, or should I put a different link?

**Comment by TheLegendofSaram** [comment]
Ohh thanks!! Yeah the GitHub link is more than enough

**Comment by opekope2** [comment]
Sorry for the delay. I wanted to translate the inspector comments, which are copied to the clipboard, but I didn't yet find the motivation. If you keep your fork, I'll let you know when I add new translations. Thanks for your contribution!

**Comment by opekope2** [comment]
Hello!
I updated the translations on the `dev` branch with over 70 new translations.
If you want to submit updated translations for the next OptiGUI 3 alpha release, you have at least 30 days.

**Comment by opekope2** [comment]
The translation keys for OptiGUI 3 alpha 4 are **finished**, no more additions, maybe small clarifications.
If you'd like to add translations for OptiGUI 3 alpha 4, you have at least 30 days.

For `optigui.rp_loader.warn.no_interaction_target`, here's some context. `blocks`, `entities`, `items`, `inventory`, and `unknown` will be part of V2 JSON resources (just like `texture.PATH` in OptiFine properties), so it makes sense to keep those 5 words as-is:
  ```json
  {
    "blocks": [],
    "entities": [],
    "items": [],
    "inventory": false,
    "unknown": true
  }
  ```

**Pull request merged**
