### PR TITLE
Added German Translation

### PR DESCRIPTION
**Pull request by Lucanoria**

### CODE REVIEW

**Comment by opekope2** [comment]
I will post updates to #127 when I add new translations (I will add some in OptiGUI 3), you can subscribe to that issue if you want to get notified.

**Comment by opekope2** [comment]
Hello!
I updated the translations on the `dev` branch with over 70 new translations.
I removed the old translation files as none of the old translation keys are used by OptiGUI, but I left the credits in `fabric.mod.json`, the `README`, the Modrinth and CurseForge pages in case you update them.
If you want to submit new translations for the next OptiGUI 3 alpha release, you have at least 30 days.

**Comment by Lucanoria** [comment]
Hey!
I'll take a look into it tomorrow thanks for letting me know

**Comment by opekope2** [comment]
The translation keys for OptiGUI 3 alpha 4 are **finished**, no more additions, maybe small clarifications.
If you'd like to add translations for OptiGUI 3 alpha 4, you have at least 30 days.

For `optigui.rp_loader.warn.no_interaction_target`, here's some context. `blocks`, `entities`, `items`, `inventory`, and `unknown` will be part of V2 JSON resources (just like `texture.PATH` in OptiFine properties), so it makes sense to keep those 5 words as-is:
  ```json
  {
    "blocks": [],
    "entities": [],
    "items": [],
    "inventory": false,
    "unknown": true
  }
  ```

**Pull request merged**
